void set_widget_opacity(GtkWidget *gtk_widget, WIDGET *widget);
void set_widget_height_width(GtkWidget *gtk_widget, WIDGET *widget);
void set_widget_title(GtkWidget *gtk_widget, WIDGET *widget);
void set_widget_name(GtkWidget *gtk_widget, WIDGET *widget);
void set_widget_angle(GtkWidget *gtk_widget, WIDGET *widget);
void set_widget_yalign(GtkWidget *gtk_widget, WIDGET *widget);
void set_widget_xalign(GtkWidget *gtk_widget, WIDGET *widget);
void set_widget_maxlength(GtkWidget *gtk_widget, WIDGET *widget);
void set_widget_placeholder(GtkWidget *gtk_widget, WIDGET *widget);
void addGtkWidgetToList(WIDGET *widget);
GtkWidget *getGtkWidgetById(char *gtk_widget_id);
GtkWidget *create_gtk_widget(WIDGET *widget);
void executeStartOperation(OPERATION *operation);
void executeShowOperation(OPERATION *operation);
void executePutOperation(OPERATION *operation);
void add_fixed_container_from_interface_to_List();